### ISSUE TITLE
Spatie Media - This driver does not support retrieving URLs.

### ISSUE THREAD

**Issue by musilondrej** [Azure-OSS/azure-storage-php-adapter-laravel#1]
I’m encountering an issue when trying to retrieve the URL of a file uploaded to Azure Blob Storage using the Spatie Media Library in my Laravel application. The file uploads successfully to Azure Blob Storage, but when I try to retrieve the URL, I receive the following error:

`This driver does not support retrieving URLs.`

Steps to Reproduce:
1.	Configure Azure Blob Storage in Laravel by adding a custom azure disk in config/filesystems.php.
2.	Use Spatie Media Library to upload a file to the Azure Blob Storage disk.
3.	Attempt to retrieve the file’s URL through Spatie Media Library’s getUrl() method or via Storage::url().

Thank you for your help!

**Comment by brecht-vermeersch** [comment]
Azure doesn't support permanent URLs, only temporary.

You can use something like Storage::temporaryUrl()

**Comment by musilondrej** [comment]
Thank you, @brecht-vermeersch. :) 

I was able to resolve the issue by adjusting the URL generator in Spatie Media Library. Since Azure Blob Storage doesn’t support permanent URLs and only provides temporary URLs, it was necessary to customize the default URL generator.

Here’s the custom URL generator class I implemented:
```
<?php

namespace App\Classes;

use Spatie\MediaLibrary\Support\UrlGenerator\DefaultUrlGenerator;

class CustomSpatieMediaUrlGenerator extends DefaultUrlGenerator
{
    public function getUrl(): string
    {
        $url = $this->getDisk()->temporaryUrl($this->getPathRelativeToRoot(), now()->addMinutes(5));
        return $this->versionUrl($url);
    }
}
```

To integrate this, I replaced the default generator in config/media-library.php like so:
`'url_generator' => App\Classes\CustomSpatieMediaUrlGenerator::class`
