### ISSUE TITLE
This driver does not support retrieving URLs.

### ISSUE THREAD

**Issue by chris0203** [Azure-OSS/azure-storage-php-adapter-laravel#5]
Hi there,

I just update to new version and got this error when I use

```php
Storage::disk('azure')->url($sd->media_path);
```

**Comment by brecht-vermeersch** [comment]
Duplicate of https://github.com/Azure-OSS/azure-storage-php-adapter-laravel/issues/1

**Comment by brecht-vermeersch** [comment]
I will add something to the docs about this
